"""
    AMD 官方网站
"""
import scrapy


class AMDItem(scrapy.Item):
    model = scrapy.Field()
    family = scrapy.Field()
    line = scrapy.Field()
    platform = scrapy.Field()
    opn_tray = scrapy.Field()
    opn_pib = scrapy.Field()
    launch_date = scrapy.Field()
    of_cpu_cores = scrapy.Field()
    of_threads = scrapy.Field()
    of_gpu_cores = scrapy.Field()
    compute_cores = scrapy.Field()
    base_clock = scrapy.Field()
    max_boost_clock = scrapy.Field()
    all_core_boost_speed = scrapy.Field()
    total_l1_cache = scrapy.Field()
    total_l2_cache = scrapy.Field()
    total_l3_cache = scrapy.Field()
    unlocked = scrapy.Field()
    cmos = scrapy.Field()
    package = scrapy.Field()
    socket_count = scrapy.Field()
    pci_express_version = scrapy.Field()
    thermal_solution = scrapy.Field()
    default_tdp_tdp = scrapy.Field()
    ctdp = scrapy.Field()
    max_temps = scrapy.Field()
    os_support = scrapy.Field()
    system_memory_specification = scrapy.Field()
    system_memory_type = scrapy.Field()
    memory_channels = scrapy.Field()
    mem_bw_2s_theo = scrapy.Field()
    graphics_frequency = scrapy.Field()
    gpu_base = scrapy.Field()
    graphics_model = scrapy.Field()
    graphics_core_count = scrapy.Field()
    supported_technologies = scrapy.Field()
    displayport = scrapy.Field()
    hdmi = scrapy.Field()
    dvi = scrapy.Field()
    vga = scrapy.Field()
    workload_affinity = scrapy.Field()
    create_day = scrapy.Field()
    create_time = scrapy.Field()
